apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infraestrutura base do cluster
  sourceRepos:
    - https://github.com/MatheusElis/richie-server
    - https://prometheus-community.github.io/helm-charts
    - https://charts.jetstack.io
    - https://helm.traefik.io/traefik
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
