---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBW7zUvBIg+97l9Sdf7E63XxMWI2Fq7+AjzCoUQfezFXLKRmYsnXls2X8Ellolqs1k3ci/1ssqtL0EQztyH3YaSYIj2qootpxQ8rHJKnyRlEE1G01Q3f+4F/hAP9sOm2CjIAg2O8oiS3XtSMX5x2TLmvHyzBPiEhtTWIU2t8GsuNS77l+BYO6SHbNyNQG0HzRLYFLSCecKXREmXEuUozn1+FjxIbjiT5HSFu3kfyQKb7yywTKAMddvtycBMm576yWUKEZB+O7h/5dIYSjQiJYH0rV0kAYl9Gh+z0rnUF5Xst8e22cEzDjgX9Ns3i0GW3w5uwT3QsfZnzXRRCdd2cyvSbQdskfKJK039LJNkzi7qE/2gT1h0dPRsmNsZnCdTilBe7YFYdN7mMz3xlrEpk0d3tydlJh7zMzdOMQOyUmC5CZ5OR+mDgEq+oT0Fra34M+yNRPSCkbQA5KAvHHVwleAo8AFL9q5EA5m5Wzw+1LCgRfsaIKFbkHhEGbVW+xHw7djTasz1JpVzPamNb2uqGQRtWTXU+HRWv2QZM6C1ZLvmzPMhSEJ47IwRGCudF8rlfo/5gIl9nFSg//hQmbwRIrtbmAxBzEG0u4+qngeCWy6KEo/kmuPXefwxZwQnu4M+fyNaZAhKaechwtkD7Kf0yQRb4J4UkpYiYoy+xZZb8dFLQca2H73nRdsNLwrAggqaFDKmre28pzjuqWIUG2OQAhughtRRottSOAWueaTfRowVILNccsZWbCaEzbR78Tzc6vlWE65SWw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
