apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: authentik
  labels:
    app: authentik-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: authentik-worker
  template:
    metadata:
      labels:
        app: authentik-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/goauthentik/server:2026.2.2
          args:
            - worker
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-credentials
                  key: secret-key
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: postgresql.postgresql.svc
            - name: AUTHENTIK_POSTGRESQL__PORT
              value: "5432"
            - name: AUTHENTIK_POSTGRESQL__USER
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-credentials
                  key: postgresql-password
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik
            - name: AUTHENTIK_REDIS__HOST
              value: redis.authentik.svc
          resources:
            requests:
              cpu: "50m"
              memory: "300Mi"
            limits:
              cpu: "300m"
              memory: "600Mi"
