apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:latest
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_HOST
          value: postgres.infra.svc.cluster.local
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: homelab-auth
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: homelab-auth
              key: password
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: homelab-auth
              key: username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: homelab-auth
              key: password
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "cloud.cusin-server.duckdns.org 192.168.31.55"
        - name: TRUSTED_PROXIES
          value: "10.42.0.0/16"
        - name: OVERWRITEPROTOCOL
          value: "https"
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        volumeMounts:
        - name: data
          mountPath: /var/www/html/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nextcloud-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: apps
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nextcloud
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - cloud.cusin-server.duckdns.org
    secretName: nextcloud-tls
  rules:
  - host: cloud.cusin-server.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 80
