---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-credentials
  namespace: pgadmin
spec:
  encryptedData:
    email: AgCo2vjE0YGy5x0mMtaoH2lW3EmH/5a0W/Z59XbtIklkPCYLAky/ury3fyq8Hp1eSiiX7QQ1zVh6rn67jPAp/aF/cZsxvU5k18dGg3CE6fGi4TyBCWvAPSQOhKy7vh29e8tWKSJYUBNSRnO4sVtUfcBUDGdBPcA7YF9HZQfPeofABB3NYxgLx8OjEpDuslox4ZgSPOAUbj/chEC4VEwlj3igIkCrGTHufyIpsd5U1bU2ROSbd0HHg93TVfBhmDJPrJXhlg7/kkmgzedlPFwd0sYDDztsN1Lu+loPYFVwqzsYFeX/5WzFtjiXSPt/BdLy50NPZbdEcYiOxiht7/snwFXuzRX1N8IGaBLI2iCv9i9QQ1BelXe9V8DSbNjaCW+AAG7P7vH6AkmXzn/OfWHgyOexdsbeMx5fqgqzYakncfhtsbs1DM21+QIbA5QpbU75EctVsyfB7QQbSj+xSHu7rhApI7jfyW3Jr+YMJCXGl7OSLdeU2abn2pWwmzRwn5yLKcUu+/f/dPiy++hKU7k5D3lPwWgod3W5YAk7Rgc+Tw3uRFTzemAAsULvnh5WdboCwGH4uTJDXiTUC9B6Ryh5cxOL3uLBU34Il4fxIPP7tLWI3/l3RrXpj1dyxU0Km21UHyTs2gMt/5/ola8C8JAaCMg27L7TsksFgYHidev7GgOTc6PSheGx+8JKWLWtJ9hUTLGOl8bgXGDdZm5d3ljRPf5InhBRbg==
    password: AgAKQL0kWZp2N7saa95X8U62ivTbABhLQiyqC3Lti1QdejIa0wH3xt7DdhVeVOQMOubsMD6A/5SOGZDMdYzCmQKpZNwwik3X5UmVDup0jRUwbdrClRiDX0VMCNRrOmqww/pCHVWcXNZyJ23bJuDWXoRyH4/l6r7cgDyC3mTLoU5VGFG5zEQfuMuxgyDwrSieaqR/V3ozNnveXQjBtmlpOXao8bV6UasmdSEs1UQmO2RHNsAGCiQkuN2JjTWQj4QX+7q/GS8VnjlDaC+2CdEYMSUyLtqC6gcRMPGdfvKK6Qhnl6YRIc18B1JDRrLBltn3g1XPQzURI2DCGOQOszdxNgx8QuGWqh5/YeRZ/AXybvc21ZlX3ox+mlGwhUwzzMwy6QcwNtDwNSWp0r0SBiz2bYXDpelObOQz+YtsxinCfKbseqhAwu78tqLap1XvnDZBAXDq6Q4LjEvc88CQMCz47E560nn1NxBDy5i1CgCjNv4z4e9WbUhTdZScLuB689QNvZRJ3vn2g/pBb29vv+WvxFJqBfghPv4AH1DWcebPXQSfGHky57HE9rmj8Fi8DWJ4SYGCSxLUdT9+oNsxl+cwFbUOAUsKnL0GI7LOj02j0fwA6ovY/pHiHl0AcA7uBCLw+QQxBuDxri9+wHuCZB4TKR84zgDQqjUZwrP35czDzAMg/oxFqey6vJpM3YjdSnq4NTjV+Tre1YsrRBxu
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-credentials
      namespace: pgadmin
    type: Opaque
