apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  capacity: {storage: 10Gi}
  accessModes: [ReadWriteMany]
  hostPath: {path: $HOME/data/configs/qbittorrent}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: apps
spec:
  accessModes: [ReadWriteMany]
  resources: {requests: {storage: 10Gi}}
  volumeName: qbittorrent-config-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Sao_Paulo"
        - name: WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: webui
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: apps
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: qbittorrent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
  - hosts:
    - qbittorrent.cusin-server.duckdns.org
    secretName: qbittorrent-tls
  rules:
  - host: qbittorrent.cusin-server.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent
            port:
              number: 80
