apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-config-pv
spec:
  capacity: {storage: 5Gi}
  accessModes: [ReadWriteMany]
  hostPath: {path: $HOME/data/configs/filebrowser}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config-pvc
  namespace: apps
spec:
  accessModes: [ReadWriteMany]
  resources: {requests: {storage: 5Gi}}
  volumeName: filebrowser-config-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:latest
        ports:
        - containerPort: 80
        args: ["--port", "80", "--database", "/config/filebrowser.db", "--root", "/data"]
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
      - name: config
        persistentVolumeClaim:
          claimName: filebrowser-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: apps
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: filebrowser
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
  - hosts:
    - files.cusin-server.duckdns.org
    secretName: filebrowser-tls
  rules:
  - host: files.cusin-server.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: filebrowser
            port:
              number: 80
