---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: joplin-credentials
  namespace: joplin
spec:
  encryptedData:
    joplin-db-password: AgCQzrFC9PBDK4ZbAOOF+Lbx1+tP6dcQyJ00J2u1fiI6WWuAjMmHjZrNyZJlNo9HLAk5Pz5ViiVcVN0rRUKVMCG1Fucpv2QceJRoAa6EL67tYIxEZgCePssAvtArynAWd8sqIl9Xo4e63gyCEC3xEUuVYtleY10yZ7mFMQQRcxHdRQC6CEhfRugrjifsOCyWWVBQLJC5exxspBVQ4WXtvGMd0zz8FZnnlVse2Q4MVatjUuVsPnp1bJI0lUqHSKUXmjafNRKtKwwXKxwedQ+u++rHv9ZLkjtlTc3I6C8af6AyQUBw03tQS/ZGjnxTCjgFLHUAEr8b5M6eKz603IVH4eXTSP9wVJyz0RN0FSkz5C9EwBz/DzAJWoNhx4XEINfCxon1uF0vAac71lOjEN1CZ3M43K8UGvlgW0WKygzlb2a6oyr1i49A6y2v4ZGcm9f099NnwldvkW3airl34Z2vcMozrObG3v8kNFO9GP5Jo2UQbzd0o+U2gwTAdOcACbUbMMl1NgGV1gRLEXs44nl/B5nUC2IjZp70vs+sz8RuG+zO0begj5kX0hyt5Ho4VU+sF5P9vEJ72Idpi3uzs7EfJ0vKvbUiUirC2L0y3caxwQxtucF/Ha5SWfnKv5o0T/k+gob+dXUCTJjHXTO7oLuqRYWpfvUZPxAPmOc1Y60VMUZ4X72mpzogrvQVIqDUI5EKQXrLwD2vkfhiIE2+
    postgres-superuser-password: AgB7tuy9l9q6srtW6wMcVZwOeCEMIVLN8HwCmaPJz+IF8UVlRvk4zqoyqnR/5468VwbFDZX0SqrjcNNaZGdWuvHUHvhZcE/5A8T1rL+yY/EWqf8K2MKJ8FEeed5O1bhnziI4vBykSu3zjxjxxijPET0h2zyeX5pMfZ/t/rvA5aG8cz/F5BJoNf8Lo8h/hug8AaG35wSU3oIXDJNsreH1gSB5DJWf12TkPCfM81i2vUTTdHK3QlmJG3/0yTKrP/udPceNX6ZaD5kYBb2shaWmznj9YxXxc1wHcrjolLZPMcOXQtAGe7TcTx0T2ZZ8IdN7Tc/Gbg0Ra85YWIQ+d6ZvFnr6Mp8mbLGnNSmTs4nb2p9rpRXdUrtEKLi83+hH5fl4gVGTdeauwoFW32hhf/XzqrSy4uIBySUpsR6xi4GXQVKG8hA5N+0tCATt/WmOM7HJJ5zU9YuCH6xfsuErVQsEXs2vl8MQ5oCfUl5AL2vn033S86vZ/2awCzubxNZD/8bPr7M4ZBqbz3NOZ+necdX+c5czyga5u63w33jBrvGnDFz4snFpi4cqh/uav37RowC6aOSikXQPt0tv1jVLSsJq6B1ujyv+OeyRckKVYcHU3uIMg2eR9B6hgUdrE05kDKZDZB6Fxk6s5HuAo36hiHODQHjlt5Rh7iYmbP5It6cqQ79E+IpK5FeB0HnQqgE6CQWItZI3YU10m7L5ivY9
  template:
    metadata:
      creationTimestamp: null
      name: joplin-credentials
      namespace: joplin
