---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: postgresql
spec:
  encryptedData:
    postgres-password: AgAw1ec++/PdeT4gp1+mxoLkqOsK9KEB6N3twvfx51JKK6YrcmtVr+7M0ElHsiCv8J/S7qOIIN0ZI77dF6xF6Xe1BpmVwy+KzWvyq/f17M/W+fx2M7WH4Y9DWPmZQJbyKlCiTq/iXWxLMNRlBeKFzuRdrDX64Os1eNo8nMAjJE0Td9PirPtsTfR0hVwGjbRan6w+Cs8jqqxKIFqyP5tN/SbeunFhZ8fZ4rm6Jy/w9G4Kc6udzomi61iTQ1XU1Xyd99+cLIa/OO9vpgZ3aCga6dgzgTidhv1/yDi77TeRS3FXZXU+THwD0RIcbdcN+X5zNR6FK3QbvLkuFnJojVDAFGeryFhUmdXUflqopccyQRv8SVM0zAQf/iW5i5ywNXmyPtdNSa29vsDCEhxQg0RdBtotdKvi8xt62BIcO6912HQVcau6Dlk2Tqq7M+sejcDPTA7+lgsRrsoDYWQn8eZtaAh1B6Up3eMTGQqGCPJzLEKNiazwqddSpMEu1DmreoEyD903jS8+R7k6Wwo2112GhUgvJXTEJXHV/JDDyBHaoj/MvV88PqklvcZRxfbJejysuh66uBSdCzwwWu7I1KpugH3rSyFWQuEIM+67ecx0+yprDfU+wp8L9IAQ8Zx9SKAywTmA48uOsM8R6BS/ryq/sO6sla9YfoLsXyBbQ0IroaNzn7ljROVhidTnT+jGhKrwGvCEdIlBkzoTf+aA
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: postgresql
    type: Opaque
