image:
  tag: "17"

auth:
  existingSecret: postgresql-credentials
  secretKeys:
    adminPasswordKey: postgres-password

primary:
  persistence:
    enabled: true
    existingClaim: postgresql-pvc

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

volumePermissions:
  enabled: true
