apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity: {storage: 500Gi}
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  hostPath: {path: /home/elis/data}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: apps
spec:
  accessModes: [ReadWriteMany]
  resources: {requests: {storage: 500Gi}}
  volumeName: data-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity: {storage: 100Gi}
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  hostPath: {path: /home/elis/data/nextcloud-data}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: apps
spec:
  accessModes: [ReadWriteMany]
  resources: {requests: {storage: 100Gi}}
  volumeName: nextcloud-data-pv
  storageClassName: ""