apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
      - name: calibre-web
        image: linuxserver/calibre-web:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Sao_Paulo"
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /books
        - name: downloads
          mountPath: /import
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: calibre-config-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  namespace: media
spec:
  ports:
  - port: 80
    targetPort: 8083
  selector:
    app: calibre-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-web
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
  - hosts:
    - calibre.cusin-server.duckdns.org
    secretName: calibre-tls
  rules:
  - host: calibre.cusin-server.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: calibre-web
            port:
              number: 80
