---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgCIPNXPqNtuDXbHGQqlBTmGbuny4siCGTyDjLaoI12Z3IsEReY102W+uiocYy3UjkSRtzLzlExGdncPFpXVhNZH1lhGKorbv32ZjVomGoUDixnyDdVurxxOIAqN3NMfAXXiQzkkMc7IrnNeprXdgD/3ZNws7EnYwthgXo6j1FBi1M6gqS4CawCtYMMVEsAarVd2SvNXhMws/IW/ICYEhqcx5TjGk4ZhVqVf2MMLT620+oZPTwRFcRLPvMo+R7z7/YnKfvClUAGB2BpYLpomduCbNqIaaWm4smcjjZ+nD9z5i/kPYrOQa+dLmPZTCWHP1kkixeo9ZwyLvE/fJz7QoA2Kw4+sS7h1jIxb7YO2NHxv/0ZJpYtiTThy4NeWhb9kH9wqog14NThupgNI86WiSfOOgOkFSf/w6ES8Ft06SwjoIWk7A25S8oD9vFdJekU4hBXMw5bRX1xYDrAVOx3atJL/PmxCGS8V32smo7gq/RmcdYJ3Dn51P2cGBD4RAUolUz6JhgO1upv7SdHWSek4WuTwIwUqQ3tgN9NUFsD5JMjdVVwE5oWRdWYCyNo4vrWkt1gG24SHqicAfLipzj+4qPDmuWUnyFo04IdIp9FaAsNrsdMtyEHC7ZVxI9/Hw8+QRJzifUCS+4eE0RLIHGRa6RyxOArax7v+nttNgMBj+iyXfknTTC+EpbJ208VeiriPase4Dwn4VhLZtz2+SY1sxs8mPMBUqUwFAwCDJlQmh2B7NTn6PiAAcjNU7vo7M4goFJsHit+I/r8/dyptUCA=
    admin.passwordMtime: AgBV435TSTvEPospQHGvHPWciTrbjU5zcpivYWrTGokqKD7UTsTH0RCcBVecMAdipdWSoUJFPDolp5CeMCmH0jXo52D4eVXRCXa81zFtjeRGLVbl2RggXeNjxAxXOBFyq+p6T7OR4PAcgjc01qbU93XGRB31oMwpY9fAHdo/VjRzWm+yLukYsfg9LX/3KDp8+DS9cWEkSbh6a7esga9j4k9CLULmRTfviaId5fgEOtDqiU7p/vCfasj3U09jzKrjYxabMljA79ww2biBC++8RRG+AB8HqVft5mM/i99jAXeW4QKUq6pGq97QW1SUaF0ArNp0szPYHLCxF3oEqeE6YE2m25WFgrcyY4PRyB6/YtQv2Kqr49LYeeWgrUNCSLGvAlfluNPMxFdT0/wcEzPVo4T9+De3eFMlcAELCVBdpN8RrJXJj/61Vc223heF3ltnw8oGh3DhtvgWf5hGPxF7xNaBuBD4U24yboz7A31JXrvpufX7UbJgo83LZhJI2yvVQahnpWaI6xBMd6zNLq7W7cOVybVN0ealI9eZEPqsp11klVuElIGSmYirpvN/UZ6O2QvogTKbwVMELLmkyFa4D8N6XCNaMBPVynX7Nq6EZ8rocTh29sa3LW4vUaLIb01BdSqFBTwRyfKyg0vsbj0+WzcQgBotA0lwLdkeRMpgTYJvAsTbRfZo8j1pQjI4dQbZqKx14eTqGR2zilxOxiw4E6Onjc6I4A==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
