---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgAjibs7MG/jtZZXko4RGT/Hv+iNU3wxGW3gZVNtLPO45CeFMxNupQs2yjB/ITB5QicSPNCim7TtJxd9RPQaEptJgtRCrRAmwxSamOwKveP5dRFMUyo7QDEaofQkH4X8VEcWOFauGjXfMib3WRMoL/RbVk/NCZsPFdrmowJxE2SwJjuidOVo+i0i19iiLik/suf/1Yv12wy3ZEkfkjVX/0rD0qfEMDrrc+rDuJQU/Gi53fHFbWxNKKkijmM7jegP3/6dcT68AwVka0lJGAOHBNSuxPDJink/WcZzUYzE6jj1aMlN0XD1YMyV2OCIdb4Li3W5pGKG2+jb/Kn0X7M4gbYhTYZ9H4gbuYnrZJT5p6mgql24ioRiHWW7BJ/2nPKhJ1UEg5jZcuRqXM0bRRXBNtvrYOBkP77dzkdFg/OdYq4CPgtNRfLoApyzUlj3mhZa7NeMylTHv7pxu5oVVee8RwuguqyuEhgsGErzxN5oAoxYVLAbqDjXUv9mJEWWIKUzf1Z4rt6hYjOslVwrsjhiIcUCrP+r0GdOrKiDW0w1QqnzrzsAZ0a365F1CxpdQKXpPOryx1QHsPcNZseG4Gc7RDDzJU4M2srCl5mgNZojX09rVrSejvoXHgjpZ1TPFMhAG7pp9wd7DuTKa2AqoVp7bhbEnHIpfsfZYR7ZOvyWXfFVcwaU/P61ytqOel2mfvY/Zz3/iYuk+ExyLnufytH7MJHx/XJS57zBMEf7+LsFcM+5fq+8BS48l9dZvCwbB+yKr5jv+UGm3dpvPi1SVA0=
    admin.passwordMtime: AgB4aMJVkogpEkf13XDnCcIiR6R4hCEZuEdeIh7rvGc6OJQOh63lY6B1pL6RA82nDqKTccOLxYgmgVuv7atry6i7D1C0VIDyuPFM/uTa7H2LmD0xnZTp8oBdBbt75UQSEchq4kmCFv7RKWgfXQlTSmzoTQ4gvNWRGVDJv6D4ZBWeBMZ4ttAdlHYW3ZLtqmpiAon4bvhZXYlAm3r7HZeYnYDBoR9/sJ4OhOARtRcXwfd3thslMHy8s2NEJj97WqCPfzULFzOb37HZLrSmteVHqZndI5Dk86ANM/WT7s8SYkes0eZQImQdne1UKDUwTpn0FMgdIEvpFrtGy+nVdFZZmcAr+C8dTovID3q3xVz5gj4uzxVmKGlkht1x/tAcfwKTBd12RP4JAzr4vFUgrLjmh5nOmWVUohj5GmPTPnvL9bdMc0ruc7+O5El66MypPf0eUbcRoH0R2N2LMVoRSJYP+ghHrjKnfyjz8xjKg0KxPWWXtkO7eNP+s86kQP9Xrzw2rujRj6reKyrT2sLffNB1F9FHzZYtk4Sl29bRp8ji2Pi8tVImCOxcv6yxXnOMfe7h/idtgXllcuINcwynuNcrWfNExnuRxoM+TqXb5qDiNeOJjeX47yv+sb7Le/BQf6SY8eRdsq4z+52Pt7CLU0yyeYLrY/0dsQuk3tSGm9/fHVQXdk3kPJCbnnjhNLRiUVewQR6tflQyuCm8HNkPBcnGN0p94JCz4A==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
