---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: duckdns-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBz5hMXEOIvbBQJ5OLXhe7JHiqXjOUxhO6IPMnI1V9Alm9ACHBLHsPUOBBLRrbOsZ+j1TGlj60OBKQO6PhQcyoyCOnN4V0vf5lOKAPiFN5Puzz0pCAjVukjY1RzhMB6XEFLNdy99ys1aHt4lXF+cQL0gDf1F1MBCn1vCEatCVNJJPnfEEQds4+IsXY8tT/hzt3LTkTCeEj6RbEfKH5eQREiQZ5lMy6rMpAQWpaFnFv6hkXnAPojhGfy3kKSPtPlsIdPzMLDPLfUvdf82XryCMpvmFixyVM+6ifNLmC0u0coX+inZ9GNwfow5ev+Shtcq/pJDOYBo8MzGkLV3c1a7eU3zvvnG7D36p0DyRJHI8iRPLmhaCvhku9k3s+C51BBQ0zw8zdJHos2yrS2ii4OBH9wIq0PWUOFPqk4f2BCyBrCCSI5WEB5BFsqQyklXpHV3D97RBpnMyFxPSARORAj3bVXfa8qfLB6C+a6Cx1A+ZcR/WfHwGkMtkxcZ4yv2t8XFkISXPa9eUWMGAN7xEK6OW7OMU/ISHVtc2LC/1YFeoIslHOkS610grMLp0cTav2AWzZo+sVwdYv2M3+Fx29gv5U0gHFNK+s06SMIQzSn4EZnlc38/tPlYoSPDIKFTW7+TirpWjbUBl9khTkk29yx6YwQNbvS91ykP1cxpX5nsxniUMQ71ADnN5YoxM8qhl6nVr51q3QePp+q+tTUhGQS5mhRBmBvAfLouRjZT26mbNSxsk2YPDE=
  template:
    metadata:
      name: duckdns-token
      namespace: cert-manager
